package Vista;

import DTOs.PeliculaDto;
import JObjects.SideBarBuilder;
import Modelo.CarteleraModel;
import Utils.Global;
import Vista.InicioSesion;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


public class Cartelera extends javax.swing.JFrame { /**
 *  
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ // </editor-fold>
    // </editor-fold>             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartelera_jlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        soon_movies_pnl = new javax.swing.JPanel();
        profile_pnl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cartelera_jlbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cartelera_jlbl.setText("Ahora mismo en Cartelera!");

        javax.swing.GroupLayout soon_movies_pnlLayout = new javax.swing.GroupLayout(soon_movies_pnl);
        soon_movies_pnl.setLayout(soon_movies_pnlLayout);
        soon_movies_pnlLayout.setHorizontalGroup(
            soon_movies_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        soon_movies_pnlLayout.setVerticalGroup(
            soon_movies_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(soon_movies_pnl);

        profile_pnl.setBackground(new java.awt.Color(255, 102, 102));
        profile_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Comprar Boletos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Pelicula");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(profile_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartelera_jlbl))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cartelera_jlbl))
                    .addComponent(profile_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PV_Cantidad objCan = new PV_Cantidad();
        objCan.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaPeliculas ag = new VentanaPeliculas();
        ag.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     AñadirPelicula ag = new AñadirPelicula();
     ag.setVisible(true);
     setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked


    public Cartelera() throws Exception {
    initComponents();
    
    setLocationRelativeTo(null);
    setTitle("TicketNet | Cartelera de Películas | Usuario << " + Global.user.getUsername() + " >>"); 
   
    CarteleraModel carteleraModel = new CarteleraModel();
    PeliculaDto[] peliculas = carteleraModel.getAllPeliculasFromCarteleras();
    // --- START OF MODIFICATION ---
    // 1. Set the main panel to use a horizontal BoxLayout
    soon_movies_pnl.setLayout(new BoxLayout(soon_movies_pnl, BoxLayout.LINE_AXIS));
    // 2. Iterate through the movies to create and add their components
    for (int i = 0; i < peliculas.length; i++) {
        PeliculaDto pelicula = peliculas[i];

        // Create a panel for each movie with a vertical layout
        JPanel moviePanel = new JPanel();
        moviePanel.setLayout(new BoxLayout(moviePanel, BoxLayout.PAGE_AXIS));

      ImageIcon ico = new ImageIcon(
            new ImageIcon(pelicula.getLogo()).getImage().getScaledInstance(120, 180, Image.SCALE_SMOOTH)
        );
        JLabel poster = new JLabel(ico);
        poster.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel title = new JLabel(pelicula.getNombre());
        title.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        // Add poster and title to the movie's panel
        moviePanel.add(poster);
        moviePanel.add(Box.createVerticalStrut(5));
        moviePanel.add(title);

        // Add the movie panel to the main container
        soon_movies_pnl.add(moviePanel);
        soon_movies_pnl.add(Box.createHorizontalStrut(5));

        // Add a 5px horizontal gap between movies, but not after the last one
        if (i < peliculas.length - 1) {
            soon_movies_pnl.add(Box.createHorizontalStrut(5));
        }
    }
 
    jScrollPane2.setViewportView(soon_movies_pnl);
    jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
    jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    
    JPanel sidebar = new SideBarBuilder()
                         .addOption("Cartelera", () -> {
                             System.out.println("You clicked on Cartelera!");
                         })
                         .addOption("Ver Historial", () -> {
                             System.out.println("You clicked on Ver Historial");
                         })
                         .addOption("Ver promociones", () -> {
                            System.out.println("You clicked on Ver Promociones");
                         })
                         .addOption("Cerrar Sesión", () -> {
                             
                             Global.destroySession();
                             
                             new InicioSesion().setVisible(true);
                             setVisible(false);
                         })
                         .build(0, 69, 167, 500);
    
    getContentPane().add(sidebar);

    profile_pnl.setBounds(0, 0, 300, 10);
}
   
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartelera_jlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel profile_pnl;
    private javax.swing.JPanel soon_movies_pnl;
    // End of variables declaration//GEN-END:variables
}
