/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdministradorVistas;

import Modelo.CarteleraModel;
import com.raven.datechooser.DateChooser;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author cedsc
 */
public class PanelFunciones extends javax.swing.JFrame {

    private CarteleraModel carteleraModel;


    public PanelFunciones() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        
        setTitle("TicketNet | Panel de Funciones");
        
        carteleraModel = new CarteleraModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear_funcion_jbtn = new javax.swing.JButton();
        consultar_funcion_jbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crear_funcion_jbtn.setText("Abrir nueva función");
        crear_funcion_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_funcion_jbtnActionPerformed(evt);
            }
        });

        consultar_funcion_jbtn.setText("Consultar función");
        consultar_funcion_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_funcion_jbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crear_funcion_jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar_funcion_jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(crear_funcion_jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(consultar_funcion_jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultar_funcion_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_funcion_jbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultar_funcion_jbtnActionPerformed

    private void crear_funcion_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_funcion_jbtnActionPerformed

        try {
            if (carteleraModel.isThereACarteleraActivated() == false) {

                JOptionPane.showMessageDialog(
                        null,
                        "¡No hay una cartelera activada ahora mismo!",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
                
                return;
            }
            
            AddFuncion addFuncion = new AddFuncion();
            
            setVisible(false);
            addFuncion.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            
            addFuncion.setVisible(true);
            addFuncion.parent = this;
            
            addFuncion.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    addFuncion.setVisible(false);
                    
                    setVisible(true);
                }
            });
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_crear_funcion_jbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultar_funcion_jbtn;
    private javax.swing.JButton crear_funcion_jbtn;
    // End of variables declaration//GEN-END:variables
}
