/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdministradorVistas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class PanelSalas extends javax.swing.JFrame {

    public PanelSalas() throws Exception {
        initComponents();
        setLocationRelativeTo(null);

        setTitle("TicketNet | Panel de Salas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear_sala_jbtn = new javax.swing.JButton();
        consultar_salas_jbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crear_sala_jbtn.setText("Abrir nueva sala");
        crear_sala_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_sala_jbtnActionPerformed(evt);
            }
        });

        consultar_salas_jbtn.setText("Consultar salas");
        consultar_salas_jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_salas_jbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crear_sala_jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar_salas_jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(crear_sala_jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(consultar_salas_jbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultar_salas_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_salas_jbtnActionPerformed
        try {

            IndexSalas indexSala = new IndexSalas();

            setVisible(false);
            indexSala.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

            indexSala.setVisible(true);
            indexSala.parent = this;

            indexSala.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    indexSala.setVisible(false);

                    setVisible(true);
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_consultar_salas_jbtnActionPerformed

    private void crear_sala_jbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_sala_jbtnActionPerformed
        try {

            AddSala addSala = new AddSala();

            setVisible(false);
            addSala.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

            addSala.setVisible(true);
            addSala.parent = this;

            addSala.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    addSala.setVisible(false);

                    setVisible(true);
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_crear_sala_jbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultar_salas_jbtn;
    private javax.swing.JButton crear_sala_jbtn;
    // End of variables declaration//GEN-END:variables
}
